pipeline {
    agent { node { label 'AmitPC' } }
    parameters {
       string (name: 'Images' , defaultValue :'D:\\WorkSpace\\Fox8\\Dev\\FoxTestingFrameworkDev\\images' ,description: 'Paramter') 
    }
     stages {
        stage('Angular NPM') {
            steps {
            bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App
                   npm run restore'''
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App
                        npm run build'''
                        bat 'xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\localConfig.json" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App\\dist\\assets" /Y/r'
            }
        }
     }
     post {
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://autoload.bks/Login.aspx''', subject: 'Selenium Tests On Amit VM', to: 'amitbl@britannica-ks.com'
        }
    }
} 
