pipeline {
    agent { node { label 'AmitPC' } }
    parameters {
       string (name: 'Images' , defaultValue :'D:\\WorkSpace\\Fox8\\Dev\\FoxTestingFrameworkDev\\images' ,description: 'Paramter') 
    }
     stages {
        stage('Angular NPM') {
            steps {
             echo 'Nunit test'
            }
        }
     }
     post {
         always {
             nunit testResultsPattern: 'A/TestResult.xml B/TestResult.xml'
         }
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://autoload.bks/Login.aspx''', subject: 'Selenium Tests On Amit VM', to: 'amitbl@britannica-ks.com'
        }
    }
} 
