pipeline {
    agent { node { label 'Dev-CI01' } }
    parameters {
       string (name: 'Images' , defaultValue :'D:\\WorkSpace\\Fox8\\Dev\\FoxTestingFrameworkDev\\images' ,description: 'Paramter') 
    }
     stages {
            stage ('Compiling New Optimization Engine') {
            steps {
                echo 'Good'
            }
        }
     }
     post {
         always {
            step([$class: 'LogParserPublisher', failBuildOnError: true, projectRulePath: 'LogParser\\LogParserRules.txt', useProjectRule: true])
        }
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }
    }
} 
