pipeline {
    agent { node { label 'AmitPC' } }

    stages {
        stage('Parallel Selnium tests running') {
            steps {
                parallel (
                    "Urgent Cat" : {
                        bat '''@echo off
                     @echo %date% %time%
                    @echo Fox UT
                    @echo ======
                    "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" --test=BusinessScenarios.Administration  D:\\WorkSpace\\Fox8\\Dev\\FoxTestingFrameworkDev\\BusinessScenarios\\bin\\Debug\\BusinessScenarios.dll 
"'''
                    } ,


                    "Med Cat" : {
                        bat '''@echo off
                        @echo %date% %time%
                        @echo Optimization UT
                        @echo ===============
                         "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" --test=BusinessScenarios.JTO  D:\\WorkSpace\\Fox8\\Dev\\FoxTestingFrameworkDev\\BusinessScenarios\\bin\\Debug\\BusinessScenarios.dll 
"'''
                    }                 
                    
                )
            }
        }

    }

    post {
        success {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }

        failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }
    }
}
