pipeline {
    agent { node { label 'Dev-CI01' } }
    parameters {
       string (name: 'SPnumber' , defaultValue :'Fox8.9.9' ,description: 'Which SP whould you like to test ?')  
       string (name: 'Filters' , defaultValue :'Category==Sanity' ,description: 'Filter Which set of test whould you like to run') 
    }
     stages {
        stage('Getting Code From P4') {
            steps {
            bat '''@echo p4 - sync
                    @echo =========
                    p4.exe set P4CLIENT=TC_p4_DEV_WIN10_FoxAutomation_add67edfa2d0f0d1
                    p4 sync -f //depot/Releases/%SPnumber%/FoxTestingFrameworkDev/...#head'''
            }
        }
        stage('Clean Images Folders') {
            steps {
            powershell """ Remove-Item C:\\Jenkins\\workspace\\SeleniumSP1\\Images\\*.* -Force
                              Remove-Item "C:\\$SPnumber\\FoxTestingFrameworkDev\\Images\\*.*" -Force """
            }
        }
        stage('Compliling Automation project'){
            steps {
                    bat 'C:\\nuget\\nuget.exe restore "c:\\TeamCity\\buildAgent\\work\\FoxAutomation\\Releases\\%SPnumber%\\FoxTestingFrameworkDev\\FoxAutomation.sln"'
                    bat '''"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "c:\\TeamCity\\buildAgent\\work\\FoxAutomation\\Releases\\%SPnumber%\\FoxTestingFrameworkDev\\FoxAutomation.sln" /t:Clean /verbosity:minimal'''
                    bat '''"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "c:\\TeamCity\\buildAgent\\work\\FoxAutomation\\Releases\\%SPnumber%\\FoxTestingFrameworkDev\\FoxAutomation.sln" /p:Configuration=Debug'''

            }
        }
        stage('Running Selenium tests') {
            steps {
                bat '"C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe"  "C:\\%SPnumber%\\FoxTestingFrameworkDev\\BusinessScenarios\\bin\\Debug\\BusinessScenarios.dll" --where "%Filters%"'
            }
        }
     }
     post {
         always {
            powershell """ Copy-Item -Path D:\\$SPnumber\\FoxTestingFrameworkDev\\Images -Destination $WORKSPACE -Recurse -Force """
            nunit testResultsPattern: 'TestResult.xml'
            archiveArtifacts 'Images/*.*'
        }
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://qa-fox8-a.bks/Login.aspx''', subject: 'Selenium sanity Tests On $SPnumber - relevant VM is dev-win10', to: 'amitbl@britannica-ks.com,innar@britannica-ks.com,yardenr@britannica-ks.com'
        }
    }
} 
