pipeline {
    agent { node { label 'QA-VM16' } }
    parameters {
       string (name: 'SPnumber' , defaultValue :'Fox8.9.8' ,description: 'Which SP whould you like to test ?')  
       string (name: 'Filters' , defaultValue :'Category==Sanity' ,description: 'Filter Which set of test whould you like to run') 
    }
     stages {
        stage('Clean Images Folders') {
            steps {
            powershell ''' 
            write-host $SPnumber
            Remove-Item D:\\$SPnumber\\FoxTestingFrameworkDev\\Images\\*.* -Force
             '''
                              
            }
        }
     }
     post {
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://qa-fox8-a.bks/Login.aspx''', subject: 'Selenium sanity Tests On $SPnumber - relevant VM is QA-VM16', to: 'amitbl@britannica-ks.com'
        }
    }
} 
