pipeline {
    agent { node { label 'Dev-CI01' } }
    options([authorizationMatrix(['com.cloudbees.plugins.credentials.CredentialsProvider.Create:auto', 'com.cloudbees.plugins.credentials.CredentialsProvider.Delete:auto', 'com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains:auto', 'com.cloudbees.plugins.credentials.CredentialsProvider.Update:auto', 'com.cloudbees.plugins.credentials.CredentialsProvider.View:auto', 'hudson.model.Item.Build:auto', 'hudson.model.Item.Cancel:auto', 'hudson.model.Item.Configure:auto', 'hudson.model.Item.Delete:auto', 'hudson.model.Item.Discover:auto', 'hudson.model.Item.Move:auto', 'hudson.model.Item.Read:auto', 'hudson.model.Item.Workspace:auto', 'hudson.model.Run.Delete:auto', 'hudson.model.Run.Replay:auto', 'hudson.model.Run.Update:auto', 'hudson.scm.SCM.Tag:auto']), pipelineTriggers([cron('H 00 * * 0-6')])])
    stages {
        stage('Pre Build Step') {
            steps {
                powershell '''Stop-Service -Name "FoxImportTaskQueueListenerActivator"
                                Stop-Service -Name "Fox Optimization: data model builder service"
                                Stop-Service -Name "Fox Optimization: Process Orchestrator Service"
                                Stop-Service -Name "Fox Optimization: Scheduler Engine Service"'''
                bat '''@echo off
                       @echo %date% %time%
                       @echo p4 - sync
                       @echo =========
                       p4.exe set P4CLIENT=dba_DEV-CI01_182
                       p4.exe -pPerforce:1666 -udba -Pq1w2e3r$ sync -f -q //depot/Fox8/Dev...#head'''
                bat '''@echo off
                       @echo %date% %time%
                       @echo  copy Microsoft.Web.UI.WebControls.dll
                       @echo =========
                       xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\Microsoft.Web.UI.WebControls.dll" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Application\\bin\\" /Y/r'''
               powershell '''Write-host "Deleting System.Security.Cryptography.Algorithms.dll from code folder" 
                            $DllFile = "System.Security.Cryptography.Algorithms.dll"
                            Get-ChildItem -Path "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\*" -include $DllFile  -Recurse |
                            Remove-Item -Force'''
            }
        }
        stage ('Parallel Build Step') {
            steps {
                parallel (
                    "Compilining Fox" : {
                        bat 'C:\\nuget\\nuget.exe restore "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Fox.sln"'
                        bat '''"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Fox.sln" /t:Clean /verbosity:minimal'''
                        bat '''"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Fox.sln" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /verbosity:minimal'''
                    } ,
                    "NG Project" : {
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App npm run restore'''
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App npm run build'''
                        bat 'xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\localConfig.json" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxNG.App\\dist\\assets" /Y/r'
                    },
                    "Compiling Old engine" : {
                        bat 'C:\\nuget\\nuget.exe restore "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\OptimizationServer\\Code\\OptimizationServer.sln"'
                        bat '"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\OptimizationServer\\Code\\OptimizationServer.sln" /t:Clean /verbosity:minimal'
                        bat '"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\OptimizationServer\\Code\\OptimizationServer.sln" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /verbosity:minimal'
                    },
                    "Ionic App" : {
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp
                                npm cache verify'''
                        powershell '''$package = "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp\\package.json"
                                      $Config = "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp\\config.xml"
                                        Set-ItemProperty $package -name IsReadOnly -value $false
                                        Set-ItemProperty $Config -name IsReadOnly -value $false '''
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp 
                        npm install'''            
                        bat '''cd C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp 
                        npm run ionic:build'''
                        bat '''Robocopy /mir C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxApp\\www\\ C:\\inetpub\\wwwroot\\FoxApp
                                xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\FoxApp\\customSettings.json" "C:\\inetpub\\wwwroot\\FoxApp\\assets\\custom-config" /Y/r'''
                        bat 'C:\\Dev-CI01\\FoxNGAPI\\FoxNGAPI.exe'
                    },
                    "Excecuting BKS scripts" : {
                        powershell 'Copy-Item -Path \\\\jenkins\\BKSInstaller -Destination $workspace -Recurse -Force'
                        powershell '''Get-Date -Format g
                                    # BKSInstaller Property Files
                                        Remove-Item "BKSInstaller\\Installation.properties" -Force -ErrorAction SilentlyContinue
                                        Remove-Item "BKSInstaller\\KB*" -Force -Recurse -ErrorAction SilentlyContinue
                                        #Write-Host "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Scripts BKSInstaller -Force"
                                        Write-Host "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Scripts BKSInstaller -Force"
                                        write-host "Strat copying scripts to Jenkins job workspace " 
                                        Copy-Item "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Scripts" "BKSInstaller\\KBCIBuild000\\Scripts" -Recurse -Force
                                        Remove-Item "BKSInstaller\\KBCIBuild000\\Scripts\\BKSMonitor" -Force -Recurse -ErrorAction SilentlyContinue
                                        Remove-Item "BKSInstaller\\KBCIBuild000\\Scripts\\DBCreation" -Force -Recurse -ErrorAction SilentlyContinue
                                        Remove-Item "BKSInstaller\\KBCIBuild000\\Scripts\\EnterpriseEditionObjects" -Force -Recurse -ErrorAction SilentlyContinue
                                        Get-Date -Format g'''
                        powershell '''Get-Date -Format g
                                        # Create Property File:
                                        "siteName=dev-pilot.bks" | Add-Content "BKSInstaller\\Installation.properties" 
                                        #"installDB=False" | Add-Content "BKSInstaller\\Installation.properties"
                                        "installCode=False" | Add-Content "BKSInstaller\\Installation.properties"
                                        "sqlUser=sa" | Add-Content "BKSInstaller\\Installation.properties"
                                        "sqlPass=mamboo" | Add-Content "BKSInstaller\\Installation.properties"'''
                        bat '''cd BKSInstaller
                               BKSInstaller.exe'''
                    }
                )
                
            }
        }
        stage ('Compiling New Optimization Engine') {
            steps {
                powershell '''$path = "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\UnitTests\\bin"
                              Get-ChildItem $Path | Where{$_.Name -Match "20"} | Remove-Item -force -Recurse'''
                echo 'SchedulerEngine.sln'
                bat '''C:\\nuget\\nuget.exe restore "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\SchedulerEngine.sln"
                        "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\SchedulerEngine.sln" /t:Clean /verbosity:minimal
                        "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\SchedulerEngine.sln" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /verbosity:minimal /clp:parameters:Summary'''
                echo 'OptimizationService.sln'
                bat '''C:\\nuget\\nuget.exe restore "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\OptimizationService\\OptimizationService.sln"
                        "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\OptimizationService\\OptimizationService.sln" /t:Clean /verbosity:minimal
                       "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\OptimizationService\\OptimizationService.sln" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /verbosity:minimal /clp:parameters:Summary'''
                echo 'FoxOptimizationHandlers.sln'
                bat '''C:\\nuget\\nuget.exe restore "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\FoxOptimizationHandlers\\FoxOptimizationHandlers.sln"
                        "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\FoxOptimizationHandlers\\FoxOptimizationHandlers.sln" /t:Clean /verbosity:minimal
                        "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"  "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\FoxOptimizationHandlers\\FoxOptimizationHandlers.sln" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /verbosity:minimal /clp:parameters:Summary'''
                bat 'C:\\Dev-CI01\\NewEngine\\NewEngineConfig.exe'   
            }
        }
        stage ('PostBuild Step') {
            steps {
              echo 'Restore Scorm Config files '
              bat 'xcopy "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\ComDlls\\ScormEngine\\Newtonsoft.Json.dll" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Integrations\\ScormEngine\\ScormEngineInterface\\bin" /Y/R/K/O/X'
              bat 'xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\SCORMEngineSettings.config" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\Integrations\\ScormEngine\\ScormEngineInterface\\SCORMEngineSettings.config" /Y/r'
              echo 'Restore ServerNameIni file'
              bat 'xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\ServerName.ini" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxUT\\bin" /Y/r'
              echo 'Restore Customers.json'
              bat 'xcopy "\\\\bks-fs\\FoxDATA$_0\\dev-pilotCI-Config\\NewOptEngineConfig\\Customers.json" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\OptimizationService\\CustomerData\\Customers.json" /Y/r'
              echo 'Start services'
              powershell '''Start-Service -Name "Fox Optimization: data model builder service"
                            Start-Service -Name "Fox Optimization: Process Orchestrator Service"
                            Start-Service -Name "Fox Optimization: Scheduler Engine Service"
                            Start-Service -Name "FoxImportTaskQueueListenerActivator"'''
            }
        }
        stage ("UnitTests") {
            steps {
                parallel (
                    "FoxUT" : {
                        bat '''  "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxUT\\bin\\FoxUT.dll" --work:"C:\\FoxUT\\FoxUT\\TestATestResult.xml"''' 
                    } ,
                    "Old Engine" {
                        bat '''  "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\OptimizationServer\\Code\\OptimizationUT\\bin\\OptimizationUT.dll" --work:"C:\\FoxUT\\OldEngine\\TestATestResult.xml"'''
                    },
                    "New Engine" : {
                        bat '''  "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\UnitTests\\bin\\UnitTests.dll" --work:"C:\\FoxUT\\NewEngine\\TestATestResult.xml"'''
                    }

                )

            }
        }
    }

    post {
        always {
            step([$class: 'LogParserPublisher', failBuildOnError: true, projectRulePath: 'LogParser\\LogParserRules.txt', useProjectRule: true])
        }
        failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Build Faliled', to: 'amitbl@britannica-ks.com;innar@britannica-ks.com;baraku@britannica-ks.com'
        }
    }
}
