pipeline {
    agent { node { label 'AmitPC' } }
     stages {
        stage('Parallel Selnium tests running' ) {
            steps {
                parallel (
                    "Urgent Cat" : {
                       archiveArtifacts 'D:/WorkSpace/Fox8/Dev/FoxTestingFrameworkDev/Images'


                    }                 
                    
                )
            }
        }
     }
     post {
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }
    }
} 
