pipeline {
    agent { node { label 'AmitPC' } }

    stages {
        stage('Parallel Selnium tests running') {
            steps {
                parallel (
                    "Test1" : {
                        bat '''@echo off
                     @echo %date% %time%
                    @echo Fox UT
                    @echo ======
                    "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" D:\\WorkSpace\\Automation1\\Automation1\\bin\\Debug\\Automation1.dll --where "Category==Urgent"'''
                    } ,


                    "Test2" : {
                        bat '''@echo off
                        @echo %date% %time%
                        @echo Optimization UT
                        @echo ===============
                        "C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe" D:\\WorkSpace\\Automation1\\Automation1\\bin\\Debug\\Automation1.dll --where "Category==Med"'''
                    }                 
                    
                )
            }
        }

    }

    post {
        success {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }

        failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://dev-pilot.bks/Login.aspx''', subject: 'Dev-Pilot Unit Tests status', to: 'amitbl@britannica-ks.com'
        }
    }
}
