pipeline {
    agent { node { label 'Dev-CI01' } }
     stages {
        stage('UT') {
            steps {
            bat 'C:\\Program Files (x86)\\NUnit.org\\nunit-console\\nunit3-console.exe "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Code\\FoxUT\\bin\\FoxUT.dll" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\OptimizationServer\\Code\\OptimizationUT\\bin\\OptimizationUT.dll" "C:\\Users\\master\\Perforce\\dba_DEV-CI01_182\\Fox8\\Dev\\Optimization\\SchedulerEngine\\UnitTests\\bin\\UnitTests.dll"'
            }
        }
     }
     post {
         always {
            nunit testResultsPattern: 'TestResult.xml'
        }
         failure {
            emailext body: '''$DEFAULT_CONTENT
                            The site can be reached at:
                            http://autoload.bks/Login.aspx''', subject: 'Selenium Tests On Amit VM', to: 'amitbl@britannica-ks.com'
        }
    }
} 
